### ISSUE TITLE
Programs run through protontricks don't seem to have access to game directories

### ISSUE THREAD

**Issue by BrainBlasted** [flathub/com.github.Matoking.protontricks#4]
Hi there - I'm trying to get Skyrim SSE set up with Mod Organizer in protontricks. However, when using Explorer in prontricks to set the path to the game, I discovered that it wasn't mounted anywhere (as far as I can tell). I couldn't manager to navigate to my steam folder and point MO to my Skyrim directory.

I'm using the Steam flatpak and the protontricks flatpak. Filesystem permissions have not been modified from the defaults, so `~/.var/app/com.valvesoftware.Steam` access remains.

**Comment by Matoking** [comment]
You'll have to add permissions for the separate Steam library directories manually due to the Flatpak security model. Flatseal is probably the easiest option for this.

You can check the full path for the Steam library folders under Steam's Storage Manager (Settings -> Downloads -> Steam Library Folders -> check the path near the size utilization bar). You can add the path for each Steam library folder under Filesystem -> Other files in Flatseal.

**Comment by BrainBlasted** [comment]
I haven't changed my library path - adding `~/.var/app/com.valvesoftware.Steam/.local/share/Steam` and  `~/.local/share/Steam` in Flatseal do not work as far as I can tell. I still haven't found a way to navigate to and access them from within protontricks.

**Comment by Matoking** [comment]
Starting with Protontricks 1.7.0, the application will print warnings for Steam library directories it cannot access, which usually happens because the Flatpak sandbox has insufficient filesystem permissions. If you still have the issue, could you check if it prints anything?

**Comment by equesvasil** [comment]
> could you check if it prints anything?
`protontricks (WARNING): Flatpak version is too old (<1.12.1) to support sub-sandboxes. Disabling bwrap. --no-bwrap will be ignored.
Traceback (most recent call last):
  File "/app/bin/protontricks", line 8, in <module>
    sys.exit(cli())
  File "/app/lib/python3.9/site-packages/protontricks/cli/main.py", line 28, in cli
    main(args)
  File "/app/lib/python3.9/site-packages/protontricks/cli/util.py", line 143, in wrapper
    return cli_func(self, *args, **kwargs)
  File "/app/lib/python3.9/site-packages/protontricks/cli/main.py", line 220, in main
    run_command(
  File "/app/lib/python3.9/site-packages/protontricks/util.py", line 352, in run_command
    str(proton_app.proton_dist_path / "bin" / "wine")
TypeError: unsupported operand type(s) for /: 'NoneType' and 'str'
`

**Comment by Matoking** [comment]
> > could you check if it prints anything?
> 
> `protontricks (WARNING): Flatpak version is too old (<1.12.1) to support sub-sandboxes. Disabling bwrap. --no-bwrap will be ignored. Traceback (most recent call last): File "/app/bin/protontricks", line 8, in <module> sys.exit(cli()) File "/app/lib/python3.9/site-packages/protontricks/cli/main.py", line 28, in cli main(args) File "/app/lib/python3.9/site-packages/protontricks/cli/util.py", line 143, in wrapper return cli_func(self, *args, **kwargs) File "/app/lib/python3.9/site-packages/protontricks/cli/main.py", line 220, in main run_command( File "/app/lib/python3.9/site-packages/protontricks/util.py", line 352, in run_command str(proton_app.proton_dist_path / "bin" / "wine") TypeError: unsupported operand type(s) for /: 'NoneType' and 'str' `

@equesvasil That seems to be a different problem. Could you create a new GitHub issue for this? You can try running Protontricks with the `-v` flag for additional details. For example, could you try running the following command to trigger the error?

```
$ flatpak run com.github.Matoking.protontricks -v --gui
```
