### ISSUE TITLE
Invalid file magic number

### ISSUE THREAD

**Issue by rickt1998** [flathub/com.github.Matoking.protontricks#41]
When trying to use protontricks on my Steam Deck, I get the following error:

```
Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/protontricks/cli/util.py", line 149, in wrapper
    return cli_func(self, *args, **kwargs)
  File "/app/lib/python3.10/site-packages/protontricks/cli/main.py", line 273, in main
    proton_app = find_proton_app(
  File "/app/lib/python3.10/site-packages/protontricks/steam.py", line 756, in find_proton_app
    tool_app = find_steam_compat_tool_app(
  File "/app/lib/python3.10/site-packages/protontricks/steam.py", line 544, in find_steam_compat_tool_app
    appinfo_sections = [
  File "/app/lib/python3.10/site-packages/protontricks/steam.py", line 544, in <listcomp>
    appinfo_sections = [
  File "/app/lib/python3.10/site-packages/protontricks/steam.py", line 452, in iter_appinfo_sections
    raise SyntaxError("Invalid file magic number")
SyntaxError: Invalid file magic number


=============

Please include this entire error message when making a bug report.
Log messages:

Running inside Flatpak sandbox, version 1.12.4.
Found Steam directory at /home/deck/.local/share/Steam
Using default Steam Runtime at /home/deck/.local/share/Steam/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 1 Steam library folders
Currently logged-in Steam user: rickthepizza1
Found 7 Steam shortcuts running using Steam compatibility tools
Using 'yad' as GUI provider
```

I tried deleting and regenerating the appinfo.vdf file but this resulted in the same error.

**Comment by rickt1998** [comment]
It appears switching to the beta branch of the steam client caused this issue. Switching back to the stable branch made the error disappear.
