### ISSUE TITLE
Protontricks doesnt launch anymore

### ISSUE THREAD

**Issue by spacecowboyx** [flathub/com.github.Matoking.protontricks#77]
I've been trying forever to get this to work and it simply will not run anymore. I keep getting the following error code

```
Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/protontricks/cli/util.py", line 149, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/cli/main.py", line 241, in main
    steam_apps = get_steam_apps(
                 ^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 1253, in get_steam_apps
    steam_app = SteamApp.from_appmanifest(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 190, in from_appmanifest
    content = path.read_text(encoding="utf-8")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 1058, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/deck/.local/share/Steam/steamapps/appmanifest_400.acf'


=============

Please include this entire error message when making a bug report.
Log messages:

Running inside Flatpak sandbox, version 1.12.4.
Found Steam directory at /home/deck/.local/share/Steam
Using default Steam Runtime at /home/deck/.local/share/Steam/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 2 Steam library folders

```
I have removed and reinstalled the program and restarted my deck and it still doesn't work

**Comment by Jcoth** [comment]
I have the same kind of issue:

Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/app/lib/python3.13/site-packages/protontricks/cli/util.py", line 180, in wrapper
    return cli_func(self, *args, **kwargs)
  File "/app/lib/python3.13/site-packages/protontricks/cli/main.py", line 337, in main
    run_command(
    ~~~~~~~~~~~^
        winetricks_path=winetricks_path,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
        cwd=cwd
        ^^^^^^^
    )
    ^
  File "/app/lib/python3.13/site-packages/protontricks/util.py", line 652, in run_command
    raise RuntimeError(
    ...<2 lines>...
    )
RuntimeError: bwrap launcher crashed, returncode: 1


=============

Please include this entire error message when making a bug report.
Environment:

Protontricks version: 1.13.1
Is Flatpak sandbox: True
Is Steam Deck: False
Is SteamOS 3+: False

Log messages:

Running inside Flatpak sandbox, version 1.14.6.
Found Steam directory at /home/jcoth/.local/share/Steam
Using default Steam Runtime at /home/jcoth/.local/share/Steam/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 1 Steam library folders
Currently logged-in Steam user: jcoth
Shortcut skse64_loader.exe (2764879262) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Found 0 Steam shortcuts running using Steam compatibility tools
Using 'yad' as GUI provider
User has configured default Proton version (CompatToolMapping): proton_experimental
Found active compatibility tool: Proton Experimental
Active compatibility tool is a Proton installation
Using 'bwrap = True' as default value
Using separately installed Steam Runtime: Steam Linux Runtime 3.0 (sniper)
Running Steam Runtime using bwrap containerization.
If any problems arise, please try running the command again using the `--no-bwrap` flag and make an issue report if the problem only occurs when bwrap is in use.
Created Steam Runtime Wine binary directory at /home/jcoth/.var/app/com.github.Matoking.protontricks/cache/protontricks/proton/Proton Experimental/bin
WINE environment variable is not available. Setting WINE environment variable to Proton bundled version.
WINESERVER environment variable is not available. Setting WINESERVER environment variable to Proton bundled version
Starting bwrap launcher process: /home/jcoth/.var/app/com.github.Matoking.protontricks/cache/protontricks/proton/Proton Experimental/bin/bwrap-launcher
Terminating launcher process 5
Launcher process terminated`
